apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: loggregator-emitter
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: loggregator-emitter
    spec:
      containers:
      - name: loggregator-emitter
        image: "loggregator/emitter:latest"
        volumeMounts:
        - name: loggregator-tls-certs
          mountPath: /srv/emitter/certs
      - name: loggregator-agent
        image: "loggregator/agent:latest"
        env:
        - name: ROUTER_ADDR
          value: loggregator-router.default.svc.cluster.local:8082
        - name: ROUTER_ADDR_WITH_AZ
          value: loggregator-router.default.svc.cluster.local:8082
        - name: AGENT_PPROF_PORT
          value: "6062"
        - name: AGENT_HEALTH_ENDPOINT_PORT
          value: "6063"
        ports:
        - name: health
          containerPort: 6063
        volumeMounts:
        - name: loggregator-tls-certs
          mountPath: /srv/agent/certs
      volumes:
      - name: loggregator-tls-certs
        secret:
          secretName: loggregator-tls-certs
