apiVersion: v1
kind: Service
metadata:
  name: log-cache-headless
  namespace: oratos
  labels:
    app: log-cache
spec:
  ports:
  - port: 8080
    name: log-cache
  - port: 8081
    name: gateway
  clusterIP: None
  selector:
    app: log-cache
