apiVersion: v1
kind: Service
metadata:
  name: loggregator-rlp
  namespace: kube-system
spec:
  selector:
    app: loggregator-rlp
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
