apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: syslog-nozzle
  namespace: oratos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: syslog-nozzle
    spec:
      volumes:
      - name: loggregator-tls-certs
        secret:
          secretName: loggregator-tls-certs
      containers:
      - name: syslog-nozzle
        image: loggregator/syslog-nozzle
        imagePullPolicy: Always
        volumeMounts:
        - name: loggregator-tls-certs
          mountPath: /srv/certs
          readOnly: true
        env:
        - name: LOGS_PROVIDER_ADDR
          value: loggregator-rlp.oratos.svc.cluster.local:8082
        # - name: NAMESPACE
        #   value: oratos
        # - name: SYSLOG_DESTINATION
        #   value: some-syslog-endpoint
